# ---- Build stage ----
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


# ---- Production stage ----
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY migrations ./migrations

RUN apk add --no-cache postgresql-client

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/index.js"]